### ISSUE TITLE
Adhere to gRPC error code statuses

### ISSUE THREAD

**Issue by joshcarp** [connectrpc/otelconnect-go#122]
https://github.com/open-telemetry/opentelemetry-specification/pull/3333 introduced a breaking change to the OpenTelemetry semantic conventions for gRPC so this should be implemented

**Comment by joshcarp** [comment]
gRPC Status Code | SpanKind.SERVER Span Status | SpanKind.CLIENT Span Status
-- | -- | --
OK | unset | unset
CANCELLED | unset | Error
UNKNOWN | Error | Error
INVALID_ARGUMENT | unset | Error
DEADLINE_EXCEEDED | Error | Error
NOT_FOUND | unset | Error
ALREADY_EXISTS | unset | Error
PERMISSION_DENIED | unset | Error
RESOURCE_EXHAUSTED | unset | Error
FAILED_PRECONDITION | unset | Error
ABORTED | unset | Error
OUT_OF_RANGE | unset | Error
UNIMPLEMENTED | Error | Error
INTERNAL | Error | Error
UNAVAILABLE | Error | Error
DATA_LOSS | Error | Error
UNAUTHENTICATED | unset | Error

**Comment by dragon3** [comment]
Hi,
I've just created a pull request to fix this issue 👉 https://github.com/connectrpc/otelconnect-go/pull/144

Please take a look when you get a chance 🙏 
Thank you!
