### ISSUE TITLE
How to get metrcis?

### ISSUE THREAD

**Issue by blackmarllbor0** [connectrpc/otelconnect-go#172]
I take an example from the documentation, but I can't figure out how I can get metrics or traces

**Comment by emcfarlane** [comment]
To export metrics you'll want to use an appropriate otel [exporter](https://opentelemetry.io/docs/languages/go/getting-started/). You may find this tutorial helpful in setting up `otelconnect-go`: https://opentelemetry.io/docs/languages/go/getting-started/ . The [example in the go docs](https://pkg.go.dev/connectrpc.com/otelconnect#readme-an-example) uses the global settings but can be applied through options also.
