### ISSUE TITLE
Add custom tag to request metric

### ISSUE THREAD

**Issue by renyijiu** [connectrpc/otelconnect-go#174]
The service is currently developed using connectrpc, and then plugged into the package to get the metrics, like `rpc_server_request_size_bytes_bucket{otel_scope_name="connectrpc.com/otelconnect",otel_scope_version="semver:0.6.0-dev",rpc_grpc_status_code="0",rpc_method="GetProject",rpc_service="projectService",rpc_system="grpc",le="0"} 0
`

but i want to read specific fields from the request header and add them to metrics (example: orgId), I wonder if this operation is supported? 

the init code:
```golang
	exporter, err := prometheus.New()
	if err != nil {
		log.Fatalf("unable to create promethe expoter")
	}
	// add custom label to all metrics

	meterProvider := metric.NewMeterProvider(metric.WithReader(exporter),
		metric.WithResource(
			resource.NewWithAttributes(
				semconv.SchemaURL,
				semconv.ServiceNameKey.String("your-service-name"),
				attribute.String("environment", "demo"),
			),
		),
	)
	otelInterceptor, err := otelconnect.NewInterceptor(
		otelconnect.WithMeterProvider(meterProvider),
		otelconnect.WithoutServerPeerAttributes(),
	)
```

**Comment by srikrsna-buf** [comment]
Adding a metric attribute is documented [here](https://opentelemetry.io/docs/languages/go/instrumentation/#adding-attributes), it can be done via an interceptor.

**Comment by jhump** [comment]
Closing this issue since I think @srikrsna-buf's response above contains the answer. @renyijiu, leave a comment if you need more information.

**Comment by renyijiu** [comment]
Thanks, I understand that this can be done when customizing the metric, but I would like to know if there is a way to add custom attributes to the library's default metrics, such as the metric data provided with the `requests_per_rpc` prefix by default
